### ISSUE TITLE
'./setting.json' dosen't exist

### ISSUE THREAD

**Issue by sookcha** [wadecon/wadecon#2]
Got the error below : 
➜  wadecon git:(master) ✗ node server.js
module.js:338
    throw err;
    ^
Error: Cannot find module './setting.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sookcha/Desktop/Dev/wadecon/server.js:23:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

Although `setting.json` file can contain some sensitive information, you guys need to provide `setting.json` file with essential structure.

**Comment by yoongun** [comment]
여긴 와동 개발자들의 서식지 -> 한글을 씁시다. ( 영어 읽기 귀찮음 )

**Comment by dolsup** [comment]
언어 사대주의자에게 내줄 답변은 ㅇ벗느니라.

**Comment by sookcha** [comment]
아니 이게 무슨...!

**Comment by yoongun** [comment]
set.뭐시기를 잘 찾아보고 그럴듯하게 json 파일을 채우면 됨

**Comment by sookcha** [comment]
불친절함..!

**Comment by dolsup** [comment]
{
    "db": {
        "user": "",
        "password": "",
        "database": "wadecon"
    },
    "fb": {
        "secret": ""   // 얼굴책 인증을 위한 앱 시크릿
    },
    "host": "localhost",
    "port": 3000,
    "expire": 600  // 세션 만료 (초)
}
